import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import heroImage from '../assets/images/hero-image.png'
import twitterIcon from '../assets/images/twitter.png'
import instaIcon from '../assets/images/instagram.png'
import facebookIcon from '../assets/images/facebook.png'
import youtubeIcon from '../assets/images/youtube.png'
import newsTitle from '../assets/images/news-title.png'
import { Swiper, SwiperSlide } from 'swiper/react' //カルーセル用のタグをインポート
import SwiperCore, { Pagination, Navigation } from 'swiper' //使いたい機能をインポート
import 'swiper/css'
import dum1 from '../assets/images/dum1.png'
import dum2 from '../assets/images/dum2.png'
import dum3 from '../assets/images/dum3.png'

SwiperCore.use([Pagination, Navigation]) 

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>CHANG-MISA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.hero}>
          <div className={styles.heroHeader}></div>
          <Image className={styles.heroImage} src={heroImage} alt="" />
          <div className={styles.heroFooter}>
            <ul>
              <li><a href=""><Image src={twitterIcon} alt=""/></a></li>
              <li><a href=""><Image src={facebookIcon} alt=""/></a></li>
              <li><a href=""><Image src={instaIcon} alt=""/></a></li>
              <li><a href=""><Image src={youtubeIcon} alt=""/></a></li>
            </ul>
          </div>
        </div>
        <div className={styles.news}>
          <Image className={styles.title} src={newsTitle} alt=""/>
          <div className={styles.swiperContainer}>
            <Swiper
            spaceBetween={10}
            slidesPerView={1}
            onSlideChange={() => console.log('slide change')}
            onSwiper={(swiper) => console.log(swiper)}
          >
            <SwiperSlide><Image src={dum1} alt="" /></SwiperSlide>
            <SwiperSlide><Image src={dum2} alt="" /></SwiperSlide>
            <SwiperSlide><Image src={dum3} alt="" /></SwiperSlide>
            <SwiperSlide><Image src={dum1} alt="" /></SwiperSlide>
          </Swiper>
          </div>
        </div>
      </main>
    </div>
  )
}
