import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import heroImage from '../assets/images/hero-image.png'
import twitterIcon from '../assets/images/twitter.png'
import instaIcon from '../assets/images/instagram.png'
import facebookIcon from '../assets/images/facebook.png'
import youtubeIcon from '../assets/images/youtube.png'
import newsTitle from '../assets/images/news-title.png'
import { Swiper, SwiperSlide } from 'swiper/react' //カルーセル用のタグをインポート
import SwiperCore, { Pagination, Navigation } from 'swiper' //使いたい機能をインポート
import 'swiper/css'
import Slider from 'react-slick'
import "slick-carousel/slick/slick.css"; 
import "slick-carousel/slick/slick-theme.css";
import dum1 from '../assets/images/dum1.png'
import dum2 from '../assets/images/dum2.png'
import dum3 from '../assets/images/dum3.png'
import worksTitle from '../assets/images/works-title.png'
import youtubeDum from '../assets/images/youtube-dum.png'
import discographyTitle from '../assets/images/discography-title.png'
import disDum1 from '../assets/images/dis-dum1.png'
import disDum2 from '../assets/images/dis-dum2.png'
import disDum3 from '../assets/images/dis-dum3.png'
import disDum4 from '../assets/images/dis-dum4.png'
import aboutTitle from '../assets/images/about-title.png'
import profile from '../assets/images/profile.png'
import contactTitle from '../assets/images/contact-title.png'
import footerLogo from '../assets/images/footer-logo.png'

SwiperCore.use([Pagination, Navigation]) 

const inter = Inter({ subsets: ['latin'] })

/* <Swiper
  spaceBetween={0}
  slidesPerView={1}
  centeredSlides={true}
  loop={true}
  onSlideChange={() => console.log('slide change')}
  onSwiper={(swiper) => console.log(swiper)}
  >
  <SwiperSlide><Image src={dum1} alt="" /></SwiperSlide>
  <SwiperSlide><Image src={dum2} alt="" /></SwiperSlide>
  <SwiperSlide><Image src={dum3} alt="" /></SwiperSlide>
  <SwiperSlide><Image src={dum1} alt="" /></SwiperSlide>
</Swiper> */

export default function Home() {

  const slideStyle = {
    height: 'auto'
  }
  
  const settings = {
    dots: false,
    arrows: false,
    centerMode: true,
    centerPadding: '40px',
    infinite: true,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1
  };
  return (
    <div>
      <Head>
        <title>CHANG-MISA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.hero}>
          <div className={styles.heroHeader}></div>
          <Image className={styles.heroImage} src={heroImage} alt="" />
          <div className={styles.heroFooter}>
            <ul>
              <li><a href=""><Image src={twitterIcon} alt=""/></a></li>
              <li><a href=""><Image src={facebookIcon} alt=""/></a></li>
              <li><a href=""><Image src={instaIcon} alt=""/></a></li>
              <li><a href=""><Image src={youtubeIcon} alt=""/></a></li>
            </ul>
          </div>
        </div>
        <div className={styles.news}>
          <Image className={styles.title} src={newsTitle} alt=""/>
          <div className={styles.swiperContainer}>
            
          <Slider {...settings}>
            <Image className={styles.slideImage} src={dum1} alt="" fill style={{objectFit: 'contain'}}/>
            <Image className={styles.slideImage} src={dum2} alt="" fill style={{objectFit: 'contain'}}/>
            <Image className={styles.slideImage} src={dum3} alt="" fill style={{objectFit: 'contain'}}/>
          </Slider>
          </div>
        </div>
        <div className={styles.works}>
          <Image className={styles.title} src={worksTitle} alt=""/>
          <div className={styles.youtubeDumContainer}>
            <Image className={styles.youtubeDum} src={youtubeDum} alt=""/>
          </div>
        </div>
        <div className={styles.discography}>
          <Image className={styles.title} src={discographyTitle} alt=""/>
          <ul className={styles.disList}>
            <li>
              <Image src={disDum1} alt=""/>
              <div className={styles.detail}>
                <h3>Mellow Sunday</h3>
                <p className={styles.format}>Format:CD</p>
                <ol>
                  <li>Ichijiku</li>
                  <li>I will fix you</li>
                  <li>Something About Us(DaftPunk cover)</li>
                  <li>S.A.U.N.A(Bonus track)</li>
                </ol>
              </div>
            </li>
            <li>
              <Image src={disDum2} alt=""/>
              <div className={styles.detail}>
                <h3>Mellow Sunday</h3>
                <p className={styles.format}>Format:CD</p>
                <ol>
                  <li>Ichijiku</li>
                  <li>I will fix you</li>
                  <li>Something About Us(DaftPunk cover)</li>
                  <li>S.A.U.N.A(Bonus track)</li>
                </ol>
              </div>
            </li>
            <li>
              <Image src={disDum3} alt=""/>
              <div className={styles.detail}>
                <h3>Mellow Sunday</h3>
                <p className={styles.format}>Format:CD</p>
                <ol>
                  <li>Ichijiku</li>
                  <li>I will fix you</li>
                  <li>Something About Us(DaftPunk cover)</li>
                  <li>S.A.U.N.A(Bonus track)</li>
                </ol>
              </div>
            </li>
            <li>
              <Image src={disDum4} alt=""/>
              <div className={styles.detail}>
                <h3>Mellow Sunday</h3>
                <p className={styles.format}>Format:CD</p>
                <ol>
                  <li>Ichijiku</li>
                  <li>I will fix you</li>
                  <li>Something About Us(DaftPunk cover)</li>
                  <li>S.A.U.N.A(Bonus track)</li>
                </ol>
              </div>
            </li>
          </ul>
        </div>
        <div className={styles.about}>
          <Image className={styles.title} src={aboutTitle} alt=""/>
          <div className={styles.content}>
            <Image src={profile} alt=""/>
            <div className={styles.detail}>
              <h3>CHANG-MiSA</h3>
              <p>Hi! l'm CHANG-MiSA.<br/>I'm singer and pianist.<br/>I love fish and I have blue fish as a pet,he is very curious fish.<br/>My favorite is KAZUNOKO(Japanese fish eggs).<br/>And I also like to read books and watching movie and jigsaw pazzles.<br/>When I write my music,I take inspiration from my favorites and my daily life.<br/>Check out my music!<br/>I'm really happy if you like it</p>
              <p>幼少期から海の上のピアニストに憧れて育つ。<br/>現在はジャズボーカリスト、またピアニストとしてホテル、レストラン、フェリーなどでのショーやBGM演奏を行いながら、オリジナル楽曲の制作、活動をしている。<br/>2021年OWL WING RECORDジャズボーカルオーディション準グランプリ受賞。<br/>2022年オリジナルミニアルバムをリリース。<br/>お魚は観るのも食べるのも釣って捌くのも好き。好物は数の子。</p>
            </div>
          </div>
        </div>
        <div className={styles.contact}>
          <Image className={styles.title} src={contactTitle} alt="" />
          <div>
            <p>ライブのご依頼、お問合せはこちらから。<br/>オンラインレッスンのお問合せ、募集もこちらより承っております。</p>
            <div className={styles.btnContainer}>
              <a href="" className={styles.btn}>CONTACT ME!</a>
            </div>
          </div>
        </div>
      </main>
      <footer className={styles.footer}>
        <div className={styles.footerInner}>
          <Image src={footerLogo} alt=""/>
          <div className={styles.detail}>
            <ul className={styles.snsList}>
              <li><a href=""><Image src={twitterIcon} alt=""/></a></li>
              <li><a href=""><Image src={facebookIcon} alt=""/></a></li>
              <li><a href=""><Image src={instaIcon} alt=""/></a></li>
              <li><a href=""><Image src={youtubeIcon} alt=""/></a></li>
            </ul>
            <p>Copyright ©CHANG-MiSA,<br/>All Rights Reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  )
}
