import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import heroImage from '../assets/images/hero-image.png'
import twitterIcon from '../assets/images/twitter.png'
import instaIcon from '../assets/images/instagram.png'
import facebookIcon from '../assets/images/facebook.png'
import youtubeIcon from '../assets/images/youtube.png'
import newsTitle from '../assets/images/news-title.png'
import { Swiper, SwiperSlide } from 'swiper/react' //カルーセル用のタグをインポート
import SwiperCore, { Pagination, Navigation } from 'swiper' //使いたい機能をインポート
import 'swiper/css'
import dum1 from '../assets/images/dum1.png'
import dum2 from '../assets/images/dum2.png'
import dum3 from '../assets/images/dum3.png'
import worksTitle from '../assets/images/works-title.png'
import youtubeDum from '../assets/images/youtube-dum.png'
import discographyTitle from '../assets/images/discography-title.png'
import disDum1 from '../assets/images/dis-dum1.png'
import disDum2 from '../assets/images/dis-dum2.png'
import disDum3 from '../assets/images/dis-dum3.png'
import disDum4 from '../assets/images/dis-dum4.png'

SwiperCore.use([Pagination, Navigation]) 

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>CHANG-MISA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.hero}>
          <div className={styles.heroHeader}></div>
          <Image className={styles.heroImage} src={heroImage} alt="" />
          <div className={styles.heroFooter}>
            <ul>
              <li><a href=""><Image src={twitterIcon} alt=""/></a></li>
              <li><a href=""><Image src={facebookIcon} alt=""/></a></li>
              <li><a href=""><Image src={instaIcon} alt=""/></a></li>
              <li><a href=""><Image src={youtubeIcon} alt=""/></a></li>
            </ul>
          </div>
        </div>
        <div className={styles.news}>
          <Image className={styles.title} src={newsTitle} alt=""/>
          <div className={styles.swiperContainer}>
            <Swiper
            spaceBetween={0}
            slidesPerView={1}
            centeredSlides={true}
            loop={true}
            onSlideChange={() => console.log('slide change')}
            onSwiper={(swiper) => console.log(swiper)}
          >
            <SwiperSlide><Image src={dum1} alt="" /></SwiperSlide>
            <SwiperSlide><Image src={dum2} alt="" /></SwiperSlide>
            <SwiperSlide><Image src={dum3} alt="" /></SwiperSlide>
            <SwiperSlide><Image src={dum1} alt="" /></SwiperSlide>
          </Swiper>
          </div>
        </div>
        <div className={styles.works}>
          <Image className={styles.title} src={worksTitle} alt=""/>
          <div className={styles.youtubeDumContainer}>
            <Image className={styles.youtubeDum} src={youtubeDum} alt=""/>
          </div>
        </div>
        <div className={styles.discography}>
          <Image className={styles.title} src={discographyTitle} alt=""/>
          <ul className={styles.disList}>
            <li><Image src={disDum1} alt=""/></li>
            <li><Image src={disDum2} alt=""/></li>
            <li><Image src={disDum3} alt=""/></li>
            <li><Image src={disDum4} alt=""/></li>
          </ul>
        </div>
      </main>
    </div>
  )
}
